ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += cc1200
  USEMODULE += cc2538_rf
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += saul_adc
endif
